server:
  port: 8989


spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
       - id: order-service
         uri: lb://ORDER-SERVICE
         predicates:
           - Path=/order/**
         filters:
           - name: CircuitBreaker
             args:
               name: order-service
               fallBackUri: forward:/orderFallBack

       - id: payment-service
         uri: lb://PAYMENT-SERVICE
         predicates:
           - Path=/payment/**
         filters:
           - name: CircuitBreaker
             args:
               name: payment-service
               fallBackUri: forward:/paymentFallBack

#actuator settings
management:
  health:
    circuitBreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      GATEWAY-SERVICE:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 60
        minimumNumberOfCalls: 6
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

eureka:
  client:
    register-with-eureka : true
    fetch-registry : true
    service-url:
      defaultZone : http://localhost:8761/eureka/
      instance:
        hostname : localhost
