server:
  port: 8989

#keycloak:
#  realm: rohi-realm
#  auth-server-url: http://localhost:8080
#  resource: springboot
#  public-client: true
#  bearer-only: true

#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/realms/Alibou
#          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/rohi_realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: springboot
      principal-attribute: preferred_username
#      routes:
#        - id: order-service
#          uri: lb://ORDER-SERVICE
#          predicates:
#            - Path=/order/**
#        - id: payment-service
#          uri: lb://PAYMENT-SERVICE
#          predicates:
#            - Path=/payment/**

#
#  zipkin:
#    base-url: http://localhost:9411/

#management:
#  tracing:
#    sampling:
#      probability: 1.0

management:
  server:
    port: 8050
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true


info:
  app:
    name: "gatewayserver"
    description: "E-Commerce Gateway Server Application"
    version: "1.0.0"







